include required("logging.conf")

auth-config {
  realm = TMT
  client-id = tmt-backend-app
}

http-server {
  port = 8084
  prefix = "CSW.apsproceduredataservice"
}

# CSW database config — used by DatabaseServiceFactory
db {
  peas {
    dataSourceClass = org.postgresql.ds.PGSimpleDataSource
    properties.serverName = localhost
    properties.portNumber = 5432
    properties.databaseName = peas
    properties.user = postgres
    properties.password = postgres
  }
}